import { Injectable, NotFoundException, Inject } from '@nestjs/common';
import { TumorTypeRepositoryPort } from '@domain/repositories/tumor-type.repository.port';
import { TumorType } from '@domain/entities/tumor-type.entity';
import { CreateTumorTypeDto } from '../dto/create-tumor-type.dto';
import { UpdateTumorTypeDto } from '../dto/update-tumor-type.dto';

@Injectable()
export class TumorTypeUseCases {
  constructor(
    @Inject('TumorTypeRepositoryPort')
    private readonly tumorTypeRepository: TumorTypeRepositoryPort,
  ) {}

  async createTumorType(
    createTumorTypeDto: CreateTumorTypeDto,
  ): Promise<TumorType> {
    const tumorType = new TumorType(
      0, // Will be generated by database
      createTumorTypeDto.name,
      createTumorTypeDto.systemAffected,
    );
    return await this.tumorTypeRepository.create(tumorType);
  }

  async getTumorTypeById(id: number): Promise<TumorType> {
    const tumorType = await this.tumorTypeRepository.findById(id);
    if (!tumorType) {
      throw new NotFoundException(`TumorType with ID ${id} not found`);
    }
    return tumorType;
  }

  async getAllTumorTypes(): Promise<TumorType[]> {
    return await this.tumorTypeRepository.findAll();
  }

  async updateTumorType(
    id: number,
    updateTumorTypeDto: UpdateTumorTypeDto,
  ): Promise<TumorType> {
    const existingTumorType = await this.tumorTypeRepository.findById(id);
    if (!existingTumorType) {
      throw new NotFoundException(`TumorType with ID ${id} not found`);
    }

    const updateData: Partial<TumorType> = {};
    if (updateTumorTypeDto.name !== undefined) {
      updateData.name = updateTumorTypeDto.name;
    }
    if (updateTumorTypeDto.systemAffected !== undefined) {
      updateData.systemAffected = updateTumorTypeDto.systemAffected;
    }

    return await this.tumorTypeRepository.update(id, updateData);
  }

  async deleteTumorType(id: number): Promise<void> {
    const tumorType = await this.tumorTypeRepository.findById(id);
    if (!tumorType) {
      throw new NotFoundException(`TumorType with ID ${id} not found`);
    }
    await this.tumorTypeRepository.delete(id);
  }
}

